Forward the standard gpg socket
Forwarding the extra socket does not seem to work with the pinentry
program. Forwarding the standard socket fixes the problem and hopefully
is still more secure than copying our GPG secrat keys to google cloud

[#176778878]

diff --git a/scripts/pair-connect b/scripts/pair-connect
--- a/scripts/pair-connect
+++ b/scripts/pair-connect
@@ -1,3 +1,79 @@
+#!/bin/bash
+
+bold=$(printf "\033[1m")
+normal=$(printf "\033[0m")
+red=$(printf "\033[31m")
+yellow=$(printf "\033[33m")
+
+if ! ssh-add -L 2>&1 >/dev/null; then
+  echo "No ssh key is loaded. Please add your ssh key before running this script!"
+  exit 1
+fi
+
+readonly GUEST_USERNAME="$(ssh-add -L | cut -d ' ' -f 3 | cut -d @ -f 1)"
+readonly SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
+
+USAGE=$(
+  cat <<EOF
+Usage: pair-connect [options]
+Options:
+  -a  address of station to connect to. Required. Ask your pair to run 'pssh' on their station and send you the output.
+  -h  this help
+EOF
+)
+
+connect() {
+  local station_address host_username
+  station_address="$1"
+  host_username="$(echo $station_address | awk -F '@' '{print $1}')"
+
+  ssh -A -R /home/"$host_username"/.gnupg/S.gpg-agent-"$GUEST_USERNAME":$HOME/.gnupg/S.gpg-agent -p 22 "$station_address"
+}
+
+main() {
+  local station_address
+  station_address=""
+
+  while getopts "ha:p:" opt; do
+    case ${opt} in
+      a)
+        station_address="$OPTARG"
+        ;;
+      h)
+        print-logo
+        echo "$USAGE"
+        exit 0
+        ;;
+      \?)
+        echo "${bold}${red}Invalid option: ${OPTARG}${normal}" 1>&2
+        print-logo
+        echo "$USAGE"
+        exit 1
+        ;;
+      :)
+        echo "${bold}${red}Invalid option: $OPTARG requires an argument${normal}" 1>&2
+        print-logo
+        echo "$USAGE"
+        exit 1
+        ;;
+    esac
+  done
+  shift $((OPTIND - 1))
+
+  if [[ -z "$station_address" ]]; then
+    echo "${bold}${red}Station address is required to connect.${normal}"
+    echo "${bold}${red}Please supply the address of the station that you want to connect to!${normal}"
+    echo "${bold}${red}Ask your pair to run 'pssh' on their station and send you the output.${normal}"
+    echo
+    echo "$USAGE"
+    exit 1
+  fi
+
+  connect "$station_address"
+}
+
+print-logo() {
+  cat <<-"EOF"
 
                     [38;m#[38;5;058m%
            [38;5;065m#[38;5;071m([38;5;071m([38;5;071m([38;5;071m([38;5;065m## ([38;5;058m%((
@@ -19,4 +95,7 @@
   / _ \___ _(_)___  / ___/__  ___  ___  ___ ____/ /_
  / ___/ _ `/ / __/ / /__/ _ \/ _ \/ _ \/ -_) __/ __/
 /_/   \_,_/_/_/    \___/\___/_//_/_//_/\__/\__/\__/
+EOF
+}
 
+main "$@"
